* Первый зал
** Камчатка в Мире
 
Камчатка -- это место встречи трёх тектонических плит. Здесь Тихоокеанская плита движется навстречу Евразийской и Североамериканской континентальным плитам. Из за этого на Камчатке происходят землетрясения, возникают и извергаются вулканы. этим связаны и горячие источники

** Какими бывают извержения

Эффузивное -- неделями или месяцами из кратера или трещины на склоне текут лавовые реки, иногда покрывая огромные территории или создавая гигантские лавовые потоки.
- Лавовое поле НТТИ
- Лавовый поток на Кизимене

Экструзивное -- лава очень вязкая, практически твёрдая, медленно выдавливается из магматического канала. Извержение длится годами и десятилетиями, при этом вулкан растёт, поднимаясь в форме купола, достигая многих сотен метров высотой. Когда купол обрушиваются по склонам вулканической горы устремляются вниз раскалённые лавины или разрушительние пирокластические потоки. При этом режим извержения сменяется на эксплозивный.
- Безымянный
- Шивелуч

Эксплозивное -- взрывное. Из кратера выбрасываются струи газов, столбы пепла и заряды вулканических бомб. Такие извержения могут носить катастрофический характер, длиться несколько минут, выбрасывая при этом невероятное количество материала и навсегда изменяя рельеф, а могут продолжаться днями и неделями, постепенно формируя шлаковые конуса.
- Карымский
- Ключевской
- Безымянный

Газовое извержение. С 2010 по 2014 годы на камчатском вулкане Горелом происходило необычное извержение. В каратере открылось жерло размером 6х8 м, из которого со скоростью более 270 м/с вырывалась струя раскалённого газа. Температура газа в 2012 г. достигла 1000 градусов С, струя светилась даже днём и раскаляла до красна стенку кратера. Однако за четыре года этого извережения не было ни одного пеплового выброса или лавового потока. Мощные раскалённые газовые струи наблюдаются многие годы и на южнокурильском вулкане Кудрявом.
- фото Горелого
- фото Кудрявого

** Режимы извержения

Во время извержения спокойное излияние лавы может чередоваться со взрывами. Переход от эффузивного извержения к эксплозивному может происходить из-за изменения расхода магмы, из-за поступления воды в магматический канал или из-за изменения содержания в магме вулканических газов. Сотрудник ИВиС ДВО РАН Ю.Б. Слёзин показал, что незначительное изменение расхода магмы во время извержения может привести к переходу от эффузивного к эксплозивному.

Нередко врывы происходят периодично, либо периодически изменяется интенсивность взрывов или фонтанирования магмы. Это приводит к тому, что шлаковые конусы вырастают слоистыми.
- Конус красный (Мутновка)
- Конус БТТИ

Сотрудник ИВиС ДВО РАН А.Ю. Озеров создал теорию, объясняющую появление таких периодичностей в режиме извержения тем, что при подъёме в магме возникают группы пузырей вулканического газа. В Институте вулканологии создана и работает самая большая в мире экспериментальная установка для моделирования вулканических извержений.
- Фото установки
- Режимы фвухфазных течений

** Какими бывают вулканы

Вулканы бывают очень разными, у каждого своя история и своя жизнь. Однако можно выделить несколько основных типов вулканических построек. Они зависят от состава извергаемых лав и от степени активности вулкана. Существует характеристика, определяющая тип вулкана, это коэффициент эксплозивности (VEI) -- доля рыхлых и раздробленных продуктов в общем количестве извергнутого материала. Она показывает насколько "взрывным" является вулкан.

Щитовые вулканы (VEI от 0.02 до 0.07). Образованы самыми горячими, текучими базальтовыми лавами. Легко растекаясь на большие расстояния, такие лавы образуют плоские и обширные постройки -- лавовые щиты. Самые большие вулканы на Земле и за её пределами -- щитовые, это вулкан Мауна-Кеа (Гавайи) и вулкан Олимп на Марсе. На Камчатке к щитовым можно отнести вулкан Горелый, Плоские сопки в Ключевкой группе вулканов, вулкан Лавовый Шиш.

Стратовулканы (VEI от  до ). Лавы этих вулканов более вязкие, они не могут растекаться на большие расстояния и застывают на склонах вулканической постройки. Перемена режимов извержений от эффузивной к эксплозивной приводит к тому, что на склоны вулкана по очереди обрушивается то поток бомб и шлака, то мощные лавовые потоки. Поэтому стратовулканы имеют слоистую структуру ("страта" на латинском означает "слой") и вырастают на значительную высоту. 

Слои лавы и пирокластики пересекают трещины -- дайки, заполняемые магмой. Дайки могут составлять до 40% объёма вулкана и укрепляют его, защищая от обрушения. Лёд вода и ветер, уносят пирокластику с вулканических склонов и обнажают дайки в виде высоких, узких и длинных стен.
- Дайки на Корякском или Толбачике
- Дайки на Мутновском вулкане

Застывая, лава в дайках сжимается и растрескивается также как растрескивается высыхающая грязь. При этом образуются причудливые плитчатые, столбчатые или глыбовые отдельности. Такое же явление можно видеть и при остввании отдельных вулканических бомб.
- поленница на Плотине
- Мыс столбчатый
- Бомба с отдельностями (лучше всего, экспонат (Дирксен? Озеров?))

Эктрузивные купола (VEI). Вязкие, остывающие ещё в магматическом канале андезитовые лавы течь уже не могут. Они медленно выдавливаются из жерла, формируя огромные купола и обелиски, короткие лавовые языки -- лобосы или причудливые формы расщепления в виде каменных лепестков или щупалец. На вулкане Шивелуч с 1980 по 2015 год экструзивный купол вырос на 600 м. Медленный рост вулканической горы может смениться стремительным катастрофическим взрывом, разрушающим и купол и более древнюю постройку вулкана. Учёные из МГУ им. Ломоносова А.А. Бармин и О.Э. Мельник объяснили каким образом скорость поступления магмы при эффузивном извержении может возрасти в миллион раз приводя к эксплозивным катастрофам.

Кальдеры (VEI). Когда случаются поистине колоссальные вулканические взрывы, выбрасывающие на поверхность более 10 куб. км. магмы, происходит обрушение кровли очаговой зоны под вулканом и на месте вулкана образуется гиганский чашеобразный провал -- кальдера. После катастрофы по краям кальдеры формируются небольшие вулканические постройки -- моногенные купола или конусы, а в её центре может начаться рост нового вулкана. Кальдеры очень широко распространены на Камчатке. Из активных вулканов в кальдерах располагаются вулканы Опала, Горелый, Карымский. К краю гиганской кальдеры Курильского озера приурочен вулкан Ильинский. 
- Горелый
- Карымский
- Курильское и Ильинский

Самым необычным вулканом кальдерного типа является вулкан Ксудач -- это восемь кальдер крупных и сравнительно небольших, наложившихся друг на друга в течение последних 40 тыс. лет. Последнее извержение этого вулкана, образовавшее большой кратер Штюбеля, случилось в 1907 г.
- Ксудач
- Поле отложений 1907 г.
  
Моногенные шлаковые конусы и купола
Эти вулканы извергаются всего однажды. По дайке на поверхность поднимается магма, извержение длится несколько месяцев, в результате формируется конус или купол 200-300 м. в высоту. После этого лава в дайке застывает и новая порция магмы по ней подняться уже не может. Если и случится извержение в этом же месте, то только если новая дайка рассечёт старую постройку, как это случилось с конусом Красным в 2012 г во время НТТИ.

Сложные постройки
У долгоживущих вулканов и вулканических центров может в течение тысяч лет несколько раз смениться режим активности или центр извержении. Так формируются сложные вулканические постройки -- вулканические хребты, кальдерные комплексы, вулканы типа сомма-везувий. Яркими примерами таких вулканов являются вулканические хребты Жупановский и Гамчен, Карымский и Кихпинычский комплексы, группа Большой Семячик. 

Сомма-везувий.
К сложным постройкам относятся Авачинский и Безымянный вулканы. Когда-то крупные вулканы оказались разрушены мощными взрывами (у Авачинского ~30 тыс. лет назад, у Безымянного -- в 1956 г), после этого в обширных взрывных кратерах выросли боле молодые постройки. Вулкан Мутновский уникален тем, что представляет собой комплекс из четырех вулканов, имеющих тип сомма-везувий.  
- Авача
- Безымянный
- Мутновка

** Вулканы и атмосфера

*** Парогазовые струи

Активный вулкан способен в сутки выбросить в атмосферу 10-15 тыс. тонн вулканических газов и на 80% эти газы состоят из воды. Откуда же взялась в вулканах эта вода? Она содержится в породах, превращающихся в магму, в форме кристаллогидратов. Молекулы воды могут встраиваться в структуры молекул других веществ, образуя прочные соединения -- кристаллогидраты. Таким образом, например застывает цемент в воде, "склеивается" крахмал в залитом водой рисе, и черствеет хлеб. (в экспозицию -- хлеб и бетон)

Недавние исследования ... показали, что на глубине ... км в недрах Земли существует целый водный пояс, настоящий подземный океан, но вода в нём находится не в виде пара или жидкости, а в связанном состоянии. Кроме глубинной воды, базальты, рождающиеся в срединноокеанических хребтах, и формирующие океаническую плиту, получают воду из океана, превращаясь под действием высоких температур в присутствии воды в серпентиниты (экспонат). Эта-то вода и приводит к плавлению океанической плиты, опускающейся под контитентальные плиты и помогает образоваться магме. По мере подъёма магмы к поверхности, вода высвобождается из содержавших её силикатов и служит движущей силой вулканических извержений. 

Вода, которая выделяется из магмы, называется ювенильной. Её можно отличить (по изотопному составу) от метеорной воды, участвующей в известном со школы круговороте воды в природе. Вулканы, приносят в атмосферу тонны ювенильной воды, воды, которой в атмосфере или не было никогда, или же которая была связана серпентинизацией более 200 млн. лет назад. Каждое облако пара, вылетающее из вулкана -- это новое облако в небе, новая вода в ручье, новый дождь в засушливой стране.

Фото. Мутновский вулкан -- фабрика по производству облаков.

Полагают, что именно вулканы создали современную атмосферу и гидросферу Земли, создали дом для всех живущих на нашей планете.

*** Вулканы и парниковый эффект




*** Сухие реки

** Вулканические озёра

Провальные колодцеобразные кратеры нередко заполняются водой. Если вулкан проявляет активность, в воду поступают вулканические газы, содержащие в себе среди всего прочего оксид серы, хлор, фтор. Эти вещества превращают воду кратерных озёр в смесь кислот.

Вода в озере Троицкого (вулкан Малый Семячик) в конце 1960-х в 1970-е годы представляла собой смесь сернистой, серной, соляной и плавиковой кислот столь концентрированную, что она растворяла стальной стержень, толщиной в палец за несколько десятков минут (pH раствора был менее 0.2). Наличие в воде плавиковой кислоты позволяло разъедать даже стекло. Вулканолог Б.И. Самойленко, исследовавший озеро в те годы, построивший карту дна и измеривший тепловой поток проходящий через озеро, получил при транспортировке образцов воды серьёзный ожог.

Чрезвычайно мелкие частички серы и оксида кремния, взвешенные в воде, образуют коллоид -- мутную смесь внешне подобную мыльному раствору. Коллоиды обладают свойством рассеивать лучи света, причём фиолетовый, синий и зелёный цвета рассеивается интенсивнее жёлтого или красного. Это явление носит название эффекта Тиндаля и приводит к тому, что на тёмном фоне или в толще коллоид имеет сине-зелёную или голубую окраску, а на просвет или на светлом фоне -- желтоватую. Этим объясняется нереально яркая окраска непрозрачной воды кратерных кислотных озёр.

С эффектом Тиндаля, окрашивающим вулканические озёра, мы сталкиваемся, наблюдая "лучи" света в утреннем лесу или в облаках. Но самое интересное, что поэтичное сравнение бездонных синих глаз с озёрами имеет физическую природу. Синими или голубыми делают глаза не краска или пигмент, а эффект Тиндаля -- рассеивание частицах белка в неокрашенной радужной оболочке глаза. Посмотрите на благородный опал или на лунный камень, их ускользающий цвет, одновременно жёлтый и голубой, это тоже результат рассения света на коллоиде оксида кремния.

Наконец, рассеивающийся на флуктуациях фоздуха свет придаёт голубой цвет дневному небу (рассение Релея) и окрашивает его в закатный багрянец утром или вечером. Таким образом, небо, синие глаза и вулканические озёра имеют синеву одной природы!

** Растительность на вулканах

** Вулканы создавшие жизнь на Земле

** Гейзеры и гидротермальные источники

** Гидротермальная энергетика

** Вулканические породы

** Минералы и руды, образующиеся на вулканах

* Второй зал
* Третий зал

** Вулканические катастрофы

Вулканические обвалы
Нередко постройки стратовулканов обваливаются приводя к крупным разрушениям у подножий,  


** Землетрясения

** Сейсмология

** Предсказание вулканических извержений

** Цунами
