* TODO Первый зал

Откуда мы знаем о том, как устроена Земля? Об этом нам рассказывают волны землетрясений, породы, минералы и газы, извергаемые вулканами, точные измерения физических полей на Земле. Сейсмология, петрология и геофизика -- эти удивительные науки помогли человеку, глядя в микроскоп или на ленту сейсмографа, заглянуть как на глубину в сотни и тысячи километров, так и на глубину сотен тысяч и миллионов лет. Они подсказывают нам откуда произошли океаны и атмофера, откуда взялась жизнь на Земле и как недра Земли могут поставить под угрозу само существование этой жизни.

О вулканах, об их завораживающей и величественной красоте, об их непостоянном нраве и долгой жизни, и о тех, кто живёт подле вулканов и изучает их рассказывает музей вулканов "Вулканариум". 

** Источник вулканизма на Камчатке

Мы живём на раскалённой, живой и подвижной планете. Её горячие пластичные недра скрыты под твердой каменной оболочкой -- литосферой. Постоянное движение пластичной и текучей внутренней оболочки Земли -- мантии, приводит к тому, что литосфера неоднородна и подвижна. Она может быть относительно тонкой и плотной, как под дном океанов, а может быть мощной и очень сложно устроенной как под материками.
Литосферные плиты медленно и непрестанно движутся, сталкиваясь, образуют возвышенности и впадины; вращаются друг относительно друга; их проплавляют поднимащиеся с глубин гигантские струи раскалённого материала -- плюмы; океанические плиты рождаются и погружаются под континентальные. Это непрестанное тектоническое движение создаёт и изменяет рельеф планеты, порождает землетрясения, создаёт вулканы и питает их.
 
Вулканы распределены на Земле не случайно. Большинство из них возникло на границах литосферных плит, а именно там, где океанические плиты погружаются под континентальные.  

Камчатка -- это место встречи не двух, а трёх литосферных плит. Здесь Тихоокеанская плита движется навстречу Евразийской и Североамериканской континентальным плитам. Причём океаническая плита движется к берегам Камчатки быстрее, чем в большинстве других мест на планете, со скоростью 7-8 см в год (сравнить эту цифру можно со скоростью роста ногтей у человека -- 3-4 см/год). С этими особенностями связана необычайная активность вулканов на Камчатке.

На полуострове насчитывают более 3000 разнообразных вулканических построек, из них около 30 считаются действующими, и в наши дни ежегодно извергаются от 4 до 7 вулканов.

** Активные и неактивные вулканы 
Действующими в российской вулканологии принято считать вулканы, которые извергались в течение последних 3,5 лет, либо те, которые в наше время проявляют очевидную активность, например, испускают пар. 
 
Откуда взялась эта цифра -- 3.5 тысячи лет? В течение более полувека на Камчатке проводится кропотливая работа по восстановлению истории активности вулканов, начатая вулканологами И. В. Мелекесцевым и О. А. Брацевой. Благодарая их труду и работе их последователей, мы знаем о том, как извергались Камчатские вулканы на протяжении последних 10-11 тыс. лет. Ни одна страна в Мире не знает историю своих вулканов настолько полно и подробно. Основным источником информации для исследователей служит пепел, который разносится во время извержений на сотни километров, а упав на землю, хранится в ней тысячи лет.

- Фото Мелекесцева
За годы работы тефрохронологи прошли боле 200 км и выкопали 10 км канав, расчисток и шурфов.

Эти исследования показали, что Камчатские вулканы, которые хранят покой на протяжении более 3,5 тысяч лет, больше уже не просыпаются. Так, потухшими считаются вулканы Вилючинский и Козельский, хорошо видные из г. Петропавловска-Камчатского. А вулкан Безымянный проснулся после 1,5 тыс. лет молчания и потряс Камчатку и всю планету колоссальным взрывом в 1956 г. 

** Какими бывают извержения

Эффузивное -- неделями или месяцами из кратера или трещины на склоне текут лавовые реки, иногда покрывая огромные территории или создавая гигантские лавовые потоки.
- Лавовое поле НТТИ
- Лавовый поток на Кизимене

Экструзивное -- лава очень вязкая, практически твёрдая, медленно выдавливается из магматического канала. Извержение длится годами и десятилетиями, при этом вулкан растёт, поднимаясь в форме купола, достигая многих сотен метров высотой. Когда купол обрушиваются по склонам вулканической горы устремляются вниз раскалённые лавины или разрушительние пирокластические потоки. При этом режим извержения сменяется на эксплозивный.
- Безымянный
- Шивелуч

Эксплозивное -- взрывное. Из кратера выбрасываются струи газов, столбы пепла и заряды вулканических бомб. Такие извержения могут носить катастрофический характер, длиться несколько минут, выбрасывая при этом невероятное количество материала и навсегда изменяя рельеф, а могут продолжаться днями и неделями, постепенно формируя шлаковые конуса.
- Карымский
- Ключевской
- Безымянный

Газовое извержение. С 2010 по 2014 годы на камчатском вулкане Горелом происходило необычное извержение. В каратере открылось жерло размером 6х8 м, из которого со скоростью более 270 м/с вырывалась струя раскалённого газа. Температура газа в 2012 г. достигла 1000 градусов С, струя светилась даже днём и раскаляла до красна стенку кратера. Однако за четыре года этого извережения не было ни одного пеплового выброса или лавового потока. Мощные раскалённые газовые струи наблюдаются многие годы и на южнокурильском вулкане Кудрявом.
- фото Горелого
- фото Кудрявого

** Режимы извержения

Во время извержения спокойное излияние лавы может чередоваться со взрывами. Переход от эффузивного извержения к эксплозивному может происходить из-за изменения расхода магмы, из-за поступления воды в магматический канал или из-за изменения содержания в магме вулканических газов. Сотрудник ИВиС ДВО РАН Ю.Б. Слёзин показал, что незначительное изменение расхода магмы во время извержения может привести к переходу от эффузивного к эксплозивному.

Нередко врывы происходят периодично, либо периодически изменяется интенсивность взрывов или фонтанирования магмы. Это приводит к тому, что шлаковые конусы вырастают слоистыми.
- Конус красный (Мутновка)
- Конус БТТИ

Сотрудник ИВиС ДВО РАН А.Ю. Озеров создал теорию, объясняющую появление таких периодичностей в режиме извержения тем, что при подъёме в магме возникают группы пузырей вулканического газа. В Институте вулканологии создана и работает самая большая в мире экспериментальная установка для моделирования вулканических извержений.
- Фото установки
- Режимы фвухфазных течений

** Какими бывают вулканы

Вулканы бывают очень разными, у каждого своя история и своя жизнь. Однако можно выделить несколько основных типов вулканических построек. Они зависят от состава извергаемых лав и от степени активности вулкана. Существует характеристика, определяющая тип вулкана, это коэффициент эксплозивности (VEI) -- доля рыхлых и раздробленных продуктов в общем количестве извергнутого материала. Она показывает насколько "взрывным" является вулкан.

Щитовые вулканы (VEI от 0.02 до 0.07). Образованы самыми горячими, текучими базальтовыми лавами. Легко растекаясь на большие расстояния, такие лавы образуют плоские и обширные постройки -- лавовые щиты. Самые большие вулканы на Земле и за её пределами -- щитовые, это вулкан Мауна-Кеа (Гавайи) и вулкан Олимп на Марсе. На Камчатке к щитовым можно отнести вулкан Горелый, Плоские сопки в Ключевкой группе вулканов, вулкан Лавовый Шиш.

Стратовулканы (VEI от  до ). Лавы этих вулканов более вязкие, они не могут растекаться на большие расстояния и застывают на склонах вулканической постройки. Перемена режимов извержений от эффузивной к эксплозивной приводит к тому, что на склоны вулкана по очереди обрушивается то поток бомб и шлака, то мощные лавовые потоки. Поэтому стратовулканы имеют слоистую структуру ("страта" на латинском означает "слой") и вырастают на значительную высоту. 

Слои лавы и пирокластики пересекают трещины -- дайки, заполняемые магмой. Дайки могут составлять до 40% объёма вулкана и укрепляют его, защищая от обрушения. Лёд вода и ветер, уносят пирокластику с вулканических склонов и обнажают дайки в виде высоких, узких и длинных стен.
- Дайки на Корякском или Толбачике
- Дайки на Мутновском вулкане

Застывая, лава в дайках сжимается и растрескивается также как растрескивается высыхающая грязь. При этом образуются причудливые плитчатые, столбчатые или глыбовые отдельности. Такое же явление можно видеть и при остввании отдельных вулканических бомб.
- поленница на Плотине
- Мыс столбчатый
- Бомба с отдельностями (лучше всего, экспонат (Дирксен? Озеров?))

Эктрузивные купола (VEI). Вязкие, остывающие ещё в магматическом канале андезитовые лавы течь уже не могут. Они медленно выдавливаются из жерла, формируя огромные купола и обелиски, короткие лавовые языки -- лобосы или причудливые формы расщепления в виде каменных лепестков или щупалец. На вулкане Шивелуч с 1980 по 2015 год экструзивный купол вырос на 600 м. Медленный рост вулканической горы может смениться стремительным катастрофическим взрывом, разрушающим и купол и более древнюю постройку вулкана. Учёные из МГУ им. Ломоносова А.А. Бармин и О.Э. Мельник объяснили каким образом скорость поступления магмы при эффузивном извержении может возрасти в миллион раз приводя к эксплозивным катастрофам.

Кальдеры (VEI). Когда случаются поистине колоссальные вулканические взрывы, выбрасывающие на поверхность более 10 куб. км. магмы, происходит обрушение кровли очаговой зоны под вулканом и на месте вулкана образуется гиганский чашеобразный провал -- кальдера. После катастрофы по краям кальдеры формируются небольшие вулканические постройки -- моногенные купола или конусы, а в её центре может начаться рост нового вулкана. Кальдеры очень широко распространены на Камчатке. Из активных вулканов в кальдерах располагаются вулканы Опала, Горелый, Карымский. К краю гиганской кальдеры Курильского озера приурочен вулкан Ильинский. 
- Горелый
- Карымский
- Курильское и Ильинский

Самым необычным вулканом кальдерного типа является вулкан Ксудач -- это восемь кальдер крупных и сравнительно небольших, наложившихся друг на друга в течение последних 40 тыс. лет. Последнее извержение этого вулкана, образовавшее большой кратер Штюбеля, случилось в 1907 г.
- Ксудач
- Поле отложений 1907 г.
  
Моногенные шлаковые конусы и купола
Эти вулканы извергаются всего однажды. По дайке на поверхность поднимается магма, извержение длится несколько месяцев, в результате формируется конус или купол 200-300 м. в высоту. После этого лава в дайке застывает и новая порция магмы по ней подняться уже не может. Если и случится извержение в этом же месте, то только если новая дайка рассечёт старую постройку, как это случилось с конусом Красным в 2012 г во время НТТИ.

Сложные постройки
У долгоживущих вулканов и вулканических центров может в течение тысяч лет несколько раз смениться режим активности или центр извержении. Так формируются сложные вулканические постройки -- вулканические хребты, кальдерные комплексы, вулканы типа сомма-везувий. Яркими примерами таких вулканов являются вулканические хребты Жупановский и Гамчен, Карымский и Кихпинычский комплексы, группа Большой Семячик. 

Сомма-везувий.
К сложным постройкам относятся Авачинский и Безымянный вулканы. Когда-то крупные вулканы оказались разрушены мощными взрывами (у Авачинского ~30 тыс. лет назад, у Безымянного -- в 1956 г), после этого в обширных взрывных кратерах выросли боле молодые постройки. Вулкан Мутновский уникален тем, что представляет собой комплекс из четырех вулканов, имеющих тип сомма-везувий.  
- Авача
- Безымянный
- Мутновка

** TODO Вулканы и атмосфера
*** Парогазовые струи
Земля -- особенная планета, она отличается от своих соседок по Солнечной системе и разнообразным рельефом, динамичным климатом и живыми обитателями. Причиной тому -- вода. На Земле вода может находиться в виде льда, жидкости и пара, перенося энергию и вещества как на поверхности, так и в недрах планеты.  
 
Активный вулкан способен в сутки выбросить в атмосферу 10-15 тыс. тонн вулканических газов и на 80% эти газы состоят из воды. Откуда же взялась в вулканах эта вода? Она содержится в породах, превращающихся в магму, в форме кристаллогидратов. Молекулы воды могут встраиваться в структуры молекул других веществ, образуя прочные соединения -- кристаллогидраты. Таким образом, например застывает цемент в воде, "склеивается" крахмал в залитом водой рисе, и черствеет хлеб. (в экспозицию -- хлеб и бетон)

Недавние исследования русских и европейских учёных показали, что на глубине 450--600 км в недрах Земли существует целый водный пояс, настоящий подземный океан, в несколько раз превосходящий по объёму Мировой Океан. Но вода в нём находится не в виде пара или жидкости, а в связанном состоянии. Кроме глубинной воды, базальты, рождающиеся в срединноокеанических хребтах, и формирующие океаническую плиту, получают воду из океана, превращаясь под действием высоких температур в присутствии воды в серпентиниты (экспонат). Эта-то вода и приводит к плавлению океанической плиты, опускающейся под контитентальные плиты и помогает образоваться магме. По мере подъёма магмы к поверхности, вода высвобождается из содержавших её силикатов и служит движущей силой вулканических извержений. 
(препринт из Nature)

Вода, которая выделяется из магмы, называется ювенильной. Её можно отличить (по изотопному составу) от метеорной воды, участвующей в известном со школы круговороте воды в природе. Вулканы, приносят в атмосферу тонны ювенильной воды, воды, которой в атмосфере или не было никогда, или же которая была связана серпентинизацией более 200 млн. лет назад. Каждое облако пара, вылетающее из вулкана -- это новое облако в небе, новая вода в ручье, новый дождь в засушливой стране.

Фото. Мутновский вулкан -- фабрика по производству облаков.

Полагают, что именно вулканы создали современную атмосферу и гидросферу Земли, создали дом для всех живущих на нашей планете.

**** Вулканы и парниковый эффект
**** Сухие реки
Характерное для вулканов явление -- сухие реки. Вода в этих реках начинает течь только после обеда, к вечеру русло заполняется и вода бежит всю ночь. К утру остаются лишь слабые ручейки, или русло вовсе оказывается сухим. И так происходит каждый день в течение всего лета, как по часам. (Мультик)

Рыхлый материал на склонах и на подножии вулкана не может удержать талую или дождевую воду, она легко просачивается внутрь пока не встретит на своём пути плотный застывший лавовый поток. К обеду таяние снежников или ледника даёт достаточно воды, чтобы пропитать ею всю рыхлую часть дна и в верховьях реки вода показывается на поверхности. Час за часом воды становится всё больше и больше, потоки мутной воды и грязи догоняют друг друга, заполняют и изменяют русло. К вечеру таяние замедляется, но воды в русле уже накопилось много и требуется несколько часов для того, чтобы вода в реке спала и снова спряталась под землю.

Большая часть сухой реки бежит под землёй вдоль водоупорного слоя. А там, где этот слой выходит на поверхность, у берега реки или в низине, она появляется, наконец, на поверхность чистыми и мощными ключами. Какие ключи можно наблюдать у подножий почти всех вулканов. По берегам реки Камчатки бьёт множество ключей, берущих начало в сухих реках Ключевской группы вулканов. Именно они дали название посёлку Ключи.

Во время извержений именно по руслам сухих рек устремляются мощные и разрушительные грязевые потоки, заплёскивающие берега на 15-30 метров!

** Вулканические озёра

Провальные колодцеобразные кратеры нередко заполняются водой. Если вулкан проявляет активность, в воду поступают вулканические газы, содержащие в себе среди всего прочего оксид серы, хлор, фтор. Эти вещества превращают воду кратерных озёр в смесь кислот.

Вода в озере Троицкого (вулкан Малый Семячик) в конце 1960-х в 1970-е годы представляла собой смесь сернистой, серной, соляной и плавиковой кислот столь концентрированную, что она растворяла стальной стержень, толщиной в палец за несколько десятков минут (pH раствора был менее 0.2). Наличие в воде плавиковой кислоты позволяло разъедать даже стекло. Вулканолог Б.И. Самойленко, исследовавший озеро в те годы, построивший карту дна и измеривший тепловой поток проходящий через озеро, получил при транспортировке образцов воды серьёзный ожог.

Чрезвычайно мелкие частички серы и оксида кремния, взвешенные в воде, образуют коллоид -- мутную смесь внешне подобную мыльному раствору. Коллоиды обладают свойством рассеивать лучи света, причём фиолетовый, синий и зелёный цвета рассеивается интенсивнее жёлтого или красного. Это явление носит название эффекта Тиндаля и приводит к тому, что на тёмном фоне или в толще коллоид имеет сине-зелёную или голубую окраску, а на просвет или на светлом фоне -- желтоватую. Этим объясняется нереально яркая окраска непрозрачной воды кратерных кислотных озёр.

С эффектом Тиндаля, окрашивающим вулканические озёра, мы сталкиваемся, наблюдая "лучи" света в утреннем лесу или в облаках. Но самое интересное, что поэтичное сравнение бездонных синих глаз с озёрами имеет физическую природу. Синими или голубыми делают глаза не краска или пигмент, а эффект Тиндаля -- рассеивание частицах белка в неокрашенной радужной оболочке глаза. Посмотрите на благородный опал или на лунный камень, их ускользающий цвет, одновременно жёлтый и голубой, это тоже результат рассения света на коллоиде оксида кремния.

Наконец, рассеивающийся на флуктуациях фоздуха свет придаёт голубой цвет дневному небу (рассение Релея) и окрашивает его в закатный багрянец утром или вечером. Таким образом, небо, синие глаза и вулканические озёра имеют синеву одной природы!

** TODO Растительность на вулканах

** Вулканы создавшие жизнь на Земле
Вулканическую силу мы обычно связываем с разрушением и гибелью. Вулканы, действительно, не раз ставили само существование жизни на Земле под вопрос. Невероятные по силе и длительности извержения, происходившите 252 млн и 60 млн лет назад, стали вероятной причиной массовых вымираний на планете. В память об этих извержениях остались обширные лавовые потоки -- Сибирские и Деканские трапповые плато, мощность которых достигает 2000 метров!

Но многое указывает на то, что ещё раньше именно вулканическая активность создала условия для возникновения и развития жизни на Земле. Один из первых вулканологов России Евгений Константинович Мархинин предложил новое направление исследований -- биовулканологию. Оно показало, что вулканы не только создали атмосферу и гидросферу нашей планеты, но и помогли заселить её.

Для появления столь сложной самоорганизующейся структуры, как живая клетка, требуются особые условия. Нужны большие контрасты химических и термодинамических потенциалов, жидкая, но тёплая вода, богатство химического состава водных растворов и смесей, периодические электрические разряды, минералы, обладающие сложной молекулярной структурой, и наконец, такое нестационарное состояние должно поддерживаться долгое время, сотни, а может быть, и тысячи лет.

Все эти условия можно наблюдать в окрестности вулканов. Горячие источники создают большие разницы температур и похожи на крепкий и кислый солевой раствор, каким был древний океан; из неглубоких магматических очагов к поверхности течёт поток самых разнообразных элементов и веществ. Частые разряды молний сопровождают извержения пепловых туч, а на поверхности глин, в которые превращают лавы горячие источники, могут появиться маленькие пузырьки -- коацерваты -- предтечи первых клеток.

Сегодня в кальдере вулкана Узон учёные могут наблюдать за тем, как живые бактерии образуют строматолиты -- окаменевшие колонии. Именно древние строматолиты позволили палеонтологам определить,что 2.5 миллиарда лет назад на Земле появились первые живые существа. Там же, на Узоне можно наблюдать как образуются сложные углеводороды и даже нефть.

** Гидротермальные источники и гейзеры
Вокруг огненных гор кипят горячие ключи, котлы, паровые струи. Такая вулканическая активность называется гидротермальной и она может продолжаться долгое время, даже после того, как вулкан перестанет извергать лаву и пепел. 

Горячая минерализованная кислая вода постепенно разрушает твёрдые лавы и пирокластику, превращая их в рыхлые изменённые породы. Вода из чёрных или серых вулканитов делает белые, жёлтые, красные рыхлые породы; измельчает их в глины, яркие как масляные краски: голубые, серые, оранжевые или карминно-красные. Вода просачивается в мельчайшие трещинки и заполняет их опалом, кварцитом, гипсом. Все эти породы непрочны и дожди со снегами легко смывают их со склонов вулкана. Так вулкан, прекратив извергаться, начинает себя постепенно разрушать, отдавая своё тело почве, рекам и морям.
-- Мутновский вулкан
-- Дзензур  

Но гидротермальная работа вулкана -- это не только разрушение. Горячая вода несёт в себе множество элементов, которые при её остывании осаждаются в виде различных соединений, а за сотни тысяч лет накапливаются в виде руд и залежей полезных ископаемых.
Кроме того, для нас вулканы приготовили уютные горячие источники, целебные косметические грязи и минеральные воды. 

Но самое яркое проявление гидротермальной активности, конечно, гейзеры. Струи пара, взметающиеся на многие метры, фонтаны необычно крупных капель, сверкающих на солнце, как жемчужины, причудливые постройки, сложенные гейзеритом, наконец, способность извергаться "по часам", всё это удивляет и потрясает!     

Как же работают гейзеры? Самоорганизующиеся периодические извержения перегретой воды можно устроить, создав глубокий канал в земле, такой, чтобы он легко заполнялся водой и в него мог поступалть горячий пар. Вода на дне канала окажется под большим давлением и из-за этого вырастет температура её кипения. Например, при глубине канала в 30 м, вода закипит только если её нагреть до 130 °С. 

Попадая в холодную воду из трещин у дна канала, пузыри пара мгновенно схлопываются, но каждый такой пузырь нагревает воду. Постепенно, вода становится горячее, пузыри пара поднимаются всё выше, вытесняя воду -- из гейзера начинает изливаться горячая, но ещё не закипевшая вода. 

Пузыри пара движутся неравномерно, большие догоняют тех что поменьше и толкают их, собирая в плотные группы, кластеры. От этого на поверхности гейзера периодически возникают многочисленные весело лопающиеся пузырьки. Во время извержения вулканов этот же процесс приводит к тому, что из кратера начинает фонтанировать лава, разбиваясь на брызги -- бомбы и лапилли.  

Горячий пар на дне канала всё же нагревает воду, и через какое-то время, она начинает вскипать. Этот процесс тоже сопровождается пульсациями: огромный пузырь пара поднимясь по каналу, попадает в воду меньшей температуры и резко схлопывается, разбиваясь на множество мелких пузырьков. Гейзер начинает "дышать", излив становится неравномерным, пульсирующим, вода в гейзере будто бы вскипает, но тут же снова успокаивается. Когда дома мы слушаем поющий самовар, шумящий электрочайник или потрескивание воды в кастрюльке на плите, мы слышим как схлапывются пузыри пара, правда, совсем небольшие.      

Наконец, вода на дне канала и в его средней части нагревается настолько сильно, что парообразование уже не остановить. Очень быстро пар начинает выталкивать и поднимать на поверхность воду, температура которой очень высока -- 110 или 120 °С. При атмосферном давлении, она попросту взрывается. И вот тут-то и происходит извержение! Из гейзера мощными струями выбрасывается вся вода, бывшая в канале, и какое-то время из него с глухим рокотом вылетает только пар с редкими каплями воды.

Вскоре гейзер успокаивается, в канал затекает холодная вода из речки, или же он заполняется потоком подземных вод. Всё начинается сначала. От того, как много воды и пара поступает в гейзер и какова глубина его канала, зависит то как долго будет нагреваться вода и через какое время будут происходит его извержения. 

Некоторые гейзеры извергаются через равные промежутки времени, некоторые, напротив, имеют сложный непостоянный нрав. Это зависит от формы канала. Если канал имеет изогнутый участок -- сифон, то даже равномерно поступающий в горячую воду пар уже будет приводить к пульсациям. Накладываясь на пульсации гейзерного режима, они могут сильно усложнить режим извержения гейзера.  

Фото капель.
Необычно крупные капли, выбрасываемые гейзером, образуются оттого, что вблизи точки кипения вода имеет малое поверхностное натяжение, которое в обычных условиях дробит струю воды в фонтане на мелкие капли.

Фото гейзеритов.


** Геотермальная энергетика

В Земле заключено огромное количество энергии в виде тепла, ведь наша планета -- это гигантский шар, разогретый до нескольких тысяч градусов. Однако поток этого тепла на поверхность невелик и воспользоваться им непросто. Вулканы представляют собой тепловые машины, которые преобразуют тепловую энергию в механическую, поднимают магму и газы на поверхность Земли, транспортируя при этом и тепло, пригодное для использования человеком. Кроме того, магма, питающая вулкан, греет воду которая просачивается в землю. Эту воду, вернее, пар, можно использовать точно также, как используется пар в ТЭС или АЭС -- пар может крутить турбину, а значит, может вырабатывать электроэнергию! 

Первые промышленные геотермальные электростанции появились в 1950-х годах в Италии, США, Японии и Новой Зеландии. В России же первую станцию такого типа построили на Камчатке и запустили в 1966 г. Паужетская ГеоТЭС была пробным камнем на котором отрабатывалась отечественная технология производства электроэнергии из тепла земли. 

- фото Сугробова, Белоусова, Дрознина

В 2017 г геотермальная энергия используется более чем в 70 странах Мира и составляет около 5% общего потребления энергии человеком. Геотермальная энергетика обеспечивает уже треть энергопотребления двух крупнейших городов Камчатки -- Петропавловска-Камчатского и Елизово. Источником тепла для этого служит месторождение парогидротерм, расположенное на северном склоне Мутновского вулкана. Использование вулканического тепла непростая задача, она требует оригинальных решений и глубоких научных знаний о том, как устроены, как возникают и как развиваются геотермальные месторождения.

** Вулканические породы

Богатство форм органических соединений -- основа жизни на Земле. Оно связано с тем, что соединять атомы углерода, кислорода и водорода, включая такие активные элементы как азот и фосфор, можно огромным множеством способов. При этом атомы образуют кольца, цепочки, ленты, спирали и совершенно невообразимые сложные формы. Так образуются сахара, жиры, РНК и ДНК и белки - вещества жизни.

Иллюстрация -- гамма-структура белка, ДНК, сахар или липид.

Есть ещё один элемент, способный образовывать большое разнообразие форм -- кремний. Вместе с кислородом кремний образует устойчивое соединение в виде треугольной пирамиды -- тетраэдра. Эти тетраэдры можно складывать в пространстве очень по-разному: в виде плотно упакованных красталлов, слоёв и лент, и весьма сложных структур. Кроме того, в построении этих структур принимают участие и атомы других элементов и молекулы воды. Так образуется огромное семейство силикатов -- минералов, имеющих в своей основе оксид кремния.

Иллюстрация -- примеры силикатов и их кристаллических структур.
- Кварц, полевой шпат, слюда, роговая обманка, асбест.

По мере того, как силикатная магма поднимается к поверхности и даже после извержения, силикаты проходят через множество превращений, меняя структуру, плавясь и кристаллизуясь, связывая или освобождая воду и примеси. Все эти превращения отражаются на свойствах извергаемых пород, определяя то каким будет тип извержения и тип формируемого вулкана.

Иллюстрации:
- Электронная фотография фенокристалла с зональностью.

Но самое удивительное это то, что человек научился изучая крохотные кристаллики породообразующих минералов, восстанавливать историю извергнутой магмы и получать представление о том, что происходит в 5, 10, 50 или 70 км под землёй. Наука, открывающая нам такую возможность, называется петрологией.

Иллюстрации:
- Фото шлифа в поляризованном свете

Один из самых распространённых минералов в недрах нашей планеты -- оливин. Но на поверхности он появляется не часто, и если бы к нам его не доставили вулканы, мы бы не знали из чего "сделана" Земля. Чистые крупные кристаллы оливина драгоценны, они называются хризолитами. Авачинский вулкан во время крупных извержений выбрасываает накопившиеся в очаговой зоне крупные скопления оливина -- оливиниты (образец). 

фото ювелирного хризолита

Горные породы, извергаемые вулканами, называются вулканитами и они бывают разными. Их основу (от 40 до 70%) составляет оксид кремния и множество разнообразных минералов, среди них соединения железа, магния, титана, калия, алюминия и многих других элементов.

В зависимости от доли оксида кремния в породе различают основные и кислые вулканиты. Типичные основные породы -- базальты. В них оксида кремния немного, и велика доля плотных темноцветных минералов. Это тёмные, иногда чёрные, плотные породы. В них часто встречаются светлые кристаллы плагиоклаза и зелёные оливины. Базальты слагают океанические плиты и не раз в истории Земли изливались на поверхность гигантскими лавовыми потоками -- траппами.  

Ярким примером кислых вулканитов является андезит -- серая, неоднородная порода со светлыми кристаллами плагиоклаза, темными амфиболами и пироксенами. Когда извергаются андезиты, вырастают лавовые купола, происходят взрывы и образуются кальдеры.  

** Пеплы и пески

Во время эксплозивных (взрывных) извержений лава дробится на мельчайшие частицы -- вулканический пепел. Это не просто песок, это частички вспененного стекла и кристаллики. 

Фото: пепел под микроскопом

Горячий пепел поднимается в небо на высоту в несколько километров. При умеренных извержениях от 5 до 8 км, во время сильных на 10-12 км. Оказавшись так высоко пепел может долго не опускаться на землю и разносится ветрами на многие сотни и тысячи километров. Катастрофические извержения могут поднять пепел на высоту в 20, 30 и даже 40 км. При этом пепловые шлейфы разносятся в пределах полушария или даже всей атмосферы. Пеплы камчатских вулканов есть и на Аляске, и во льдах Гренландии и в почвах Азии.

- экспонаты: образцы пеплов.
- фото козыревских картофельных полей.
Подпись. Попадая на почву в небольших количествах, пепел может служить минеральным удобрением.

Горные породы ручьями и реками сносятся к морским берегам. Там незамолкающий прибой постоянно перемалывает и перемывает частички этих пород, унося рыхлые, лёгкие минералы, и оставляя на берегу плотные и твёрдые. Так образуются пляжи. В большинстве мест на земле самыми твёрдвми остаются частички кварца и морские волны бьют в белые и жёлтые пляжи.

Иллюстрации 
- золотой черноморский пляж
- лоток золотоискателя (подпись: Таким же образом старатели моют золотой песок, тщательно вымывая из него легкие песчинки, оставляя в лотке тяжёлые крупицы золота)  

В районах активного вулканизма самыми тяжёлыми и твёрдыми оказываются темноцветные минералы, такие как титаномагнетит. Поэтому песок на Камчатке тёмно-серый или чёрный. Песок пляжей восточного побережья Камчатки -- это залежи титановой и железной руды. Титаномагнетит обладает магнитными свойствами, в этом можно убедиться, приблизив к чёрному камчатскому песку магнит.

-- экспонат: волжский песок, халактырский песок, магнит.

А на Гавайях и на острове Реюньон в Индийском океане, есть оливиновые пляжи, песок которых имеет зелёный цвет. В извергаемых там породах -- пикритах, очень много вкрапленников оливина. Этот минерал тоже весья плотный и твёрдый. 

-- фото Оливинового пляжа

** Минералы и руды, образующиеся на вулканах
   
Минералы образуются не только в магме. После извержения и между ними, вулкан столетиями и тысячелетиями работает как химический комбинат. Из раскалённых газов сложного состава при остывании вырастают кристаллы разнообразных веществ и соединений. Остывающие лавовые поля и кратеры расцвечиваются множеством красок.

- возгоны на лавовых полях
- возгоны в пещере

Среди появляющихся таким образом минералов есть устойчивые, а есть и такие, которые живут совсем недолго, разрушаясь на воздухе. Каждое извержение может подарить минералогам новые открытия. Камчатскими и Петербургскими исследователями были открыты, описаны и названы более сорока новых, неизвестных прежде минералов! Вулканология -- наука полная открытий!

- фото Г.А. Карпова, Л.П.Вергасовой, Филатова
- фото эксгаляционных минералов

Одним из ярких открытий, сделанных на камчатских вулканах, стало обнаружение в лавах алмазов. В лавах Авачинского вулкана сотрудник Института вулканологии Фарид Кутыев обнаружил карбонадо -- разновидность алмазов чёрного цвета. Позже, во время извержения Корякского вулкана в 2009 г., Леонид Павлович Аникин нашёл в пепле наночастицы алмазов. И, наконец, во время трещинного извержения на Толбачинском Долу в 2012-2013 гг. ему же посчастливилось обнаружить микрочастицы алмазов (до 0.7 мм) в корке лавового потока. Это привело к открытию нового механизма появления алмазов в природе.       

- фото Ф.Ш. Кутыева
- фото алмазов

Сложные постмагматические процессы происходят и в гидротермальных системах, в них тысячелетиями накапливаются металлические руды, вырастают кристаллы драгоценных камней. Вулканическая тепловая машина транспортирует и концентрирует разнообразные полезные вещества, работая как неспешный, но мощный горнообогатительный комбинат.

фото -- золото в прожилках кварца
экспонат -- блеклая руда, пирит

** Вулканический бонсаи
Когда мастер 
* TODO Второй зал

** Цвет лав

Застывшая лава не всегда бывает чёрной или серой. Оказавшись во время извержения или сразу после него на лававом потоке, вы увидите множество ярких цветов. Вдоль трещинок в остывающих потоках вырастают разноцветные красталлики и корочки, иногда они покрывают большие площади. Шлак и бомбы становятся бурыми или коричневыми. 

Но стоит приглядеться и к чёрным обломкам лавы. На ярком солнечном свете они начинают переливаться множеством сияющих цветов, тут и отлив "вороньего" крыла, и глубокий фиолетовый и золотистый. Такие яркие цвета лаве придают тончайшие прозрачные плёночки оксидов, которые образуются на её остывающей поверхности. Эти цвета зовутся цветами побежалости. Их можно видеть на металлических стружках фрезерного и токарного станков или на раскалённом на точильном камне ноже. А видим мы эти плёночки цветными по той же причине по которой цветными нам кажутся плёнка бензина в луже или мыльный пузырь -- из-за явления интерференции света.   

** Как текут лавы

Лава -- это не простая жидкость. То как она будет течь сильно зависит от её температуры, от количества в ней газа, наконец, от уклона по которому бежит лавовая река. Более того, жидкая лава обладает и свойствами твёрдого тела, она может внезапно остановить течение и перегородить саму себя. Лавовая река может образовывать множество рукавов или выстроить сама себе прямое русло и бежать ровно на протяжении многих километров, а может превратиться в бесформенную груду камней, неумолимо надвигающуюся десятиметровой стеной на лес. И всё это во время одного извержения!

Поверхность лавы остывает, теряет текучесть, становится пластичной или хрупкой. На поверхности потока образуются причудливые складки, похожие на волны ткани, или на спутанные верёвки и канаты. Внутри лавы постоянно выделяется газ и пузыри раздувают лаву как тесто. Остывшая до состаяния пластичности лава, вместо того, чтобы течь рекою, образует большие раздувающиеся подушки.



* Третий зал
** TODO Вулканические катастрофы

Вулканы живут и действуют в геологически масштабах. Они способны изменять рельеф и климат, причём не только в течение тысячелетий, но и внезапно за считанные часы или дни. В результате мощных извержений могут исчезнуть горы или реки, появиться новые озёра или острова. За последние сто лет только на Камчатке были на глазах исследователей разрушены постройки вулканов Безымянный и Шивелуч, которые потом практически восстановились. Исчезла река Сухая Хапица, но родились полуостров Такетоми (на острове Алаид в Охотском море) и полуостров Новогодний в Карымском озере. В результате извержения возникло новое озеро у подножия вулкана Кизимен. На месте лесов в Толбачинском долу разлились обширные лавовые поля площадью в десятки квадратных километров и выросло восемь новых шлаковых конусов.

Вулканизм -- это живая геология, творческая сила самой Земли. 

** TODO Землетрясения

Наблюдая за солнечной тенью в разное время года и в разных частях света уже древние люди смогли понять, что живут на круглой Земле. Более того, им удалось оценить её размеры. 
Сейчас мы знаем, что Земля состоит из слоёв -- снаружи твёрдая кора, глубже находятся пластичная мантия, жидкое ядро, а в самом центре расположено твёрдое внутренне ядро. Но откуда людям всё это известно, ведь ни заглянуть ни пробурить на глубину в тысячи километров пока невозможно?

Землетрясение -- это не только катастрофа, стихийное бедствие или пугающее явление природы. Землетрясения дали человеку возможность  "видеть" Землю насквозь, до самого центра! Случившись в одном месте, землетрясение отправляет сейсмические волны повсюду и на короткое время, как бы подсвечивает Землю изнутри. Геофизики научились регистрировать эти волны и видеть картину, которую они показывают. Таким же образом у будущих родителей есть возможность познакомиться с неродившимся ещё малышом, используя ультразвук.   

Исследование землетрясений дало нам большую часть представлений о плитах и о природе вулканизма. Но кроме этого, сейсмические сигналы рассказывают нам и о том, что происходит под землёй: как движутся плиты и как готовят извержения вулканы. Поднимающаяся к поверхности магма прокладывает себе путь в твёрдой и хрупкой коре, заставляя её растрескиваться. Это приводит к небольшим, но очень частым землетрясениям. Их появление, усиление, перемещение их очагов к поверхности предваряет извержение вулкана. 

Исследуя сесмичность вулканов мы научились давать прогнозы извережений для некоторых из них. В 1975 году сотрудникам Института вулканологии удалось за месяц предсказать начало Большого трещинного толбачинского извержения. В 2010 году не стало неожиданностью извережение вулкана Кизимен, молчавшего более 80 лет. Разрабатываются новые технологии и методы прогноза, включающие в себя не только сейсмологию, но и измерения деформации вулканических построек -- геодезию, отслеживание изменений в составе вулканических газов. 

Предсказывать вулканические извержения можно, хоть эта задача пока далека от полного решения. А вот предсказание тектонических землетрясений, связанных с движением плит, пока, увы задача практически не решаемая. Можно лишь говорить о вероятности землетрясения в том или ином районе в ближайшие, скажем, год или пять лет. Но указать через какое конкретно время, в каком месте и какой силы случится землетрясение пока не удаётся. 

Существуют системы раннего оповещения об уже случившимся землетрясении. Сейсмические волны бегут в земле и по её поверхности быстро -- со скоростями в первые километры в секнду, но, всё же не быстрее чем радиосигнал. Это значит, что расположенный в эпицентре далёкого землетрясения сейсмометр сможет передать в крупный город информацию о том что землетрясение уже произошло за 7 -- 10 секунд до того, как туда придут разрушительные волны.     

--------------------------------------------------

Виды сейсмических волн (Иллюстрация).
Продольные (P-волны) -- самые быстрые, распространяются как в твёрдых так и в жидких средах (в магме, в расплавленном ядре). 

Поперечные (S-волны) -- бегут медленнее P-волн, но самое главное, они не распространяются в жидких средах и отражаются от границ, разделяющих расплав и твёрдые породы.

Поверхностные волны возникают при встрече сейсмических волн с поверхностью. Поверхностные волны самые разрушительные. 

** TODO История сейсмологических исследований на Камчатке

** TODO Цунами  

Океан велик, но в масштабах планеты, это вcё же вовсе неглубокий водоём и по нему могут бежать волны, которые тоже имеют планетарный масштаб. Это волны цунами. 

Чем отличаются волны цунами от гигантских штормовых волн? Ведь сильные ветра могут создавать в океане волны высотой в 15 и в 25 метров. Эти волны впечатляют, но не приносят больших несчастий. На таких волнах катаются на серфингах и фотографируются на их фоне. Однако волны цунами высотой в 8-10 метров уже считаются разрушительными, а в 15-25 метров -- катастрофическими!

Эти волны существенно отличаются по энергии. Скорость сильной ветровой волны 20 м/c, скорость волны цунами -- 200 м/с (700 км/ч)! Длина ветровой волны (расстояние между гребнями) достикает 500 м, длина волны цунами -- сотни километров! Даже при очень сильном ветре в движение приходят первые десятки метров воды, в волне цунами движется вся толща океана -- 3-4 километра! Волна цунами несёт с огромной скоростью колоссальный объём воды.

В результате ветровые волны разрушают и заполняют лишь полосу прибоя -- первые сотни метров от воды, а волны цунами высотой в 20 м могут продвинуться вглубь суши более чем на 10 километров! Когда подходит такая волна море превращается в стремительную реку, неудержимо двигаясь, не ощущая препятствий.
